### ISSUE TITLE
Data import from sql file

### ISSUE THREAD

**Issue by manoharbhattarai** [danfe-tech/simple-libs#5]
I am using this library which is very helpful in using JDBC transactions. It would be great if we get a feature to execute sql script file which will create the tables at once. Currently we have to create tables manually which is error prone. So it would be great feature to add the database sql script file and execute to create the tables automatically.

Regards,
Manohar Bhattarai

**Comment by ctizmah** [comment]
While using JDBCTemplate for executeUpdate with list of QueryParameter, I got SQLException stating inclusion of the Unexpected token when there is at least one parameter, whose name begins with one of the earlier parameter.

Some of the list of QueryParameter that caused exception are : ..,enrolled,enrolledOn,enrolledFrom,..

Caught Exception:
java.sql.SQLException: Unexpected token: 1 in statement [INSERT INTO beneficiaries(id_number, id_type, fullname, zone, district, vdc_or_municipality, ward_no, enrolled, enrolled_on, enrolled_from) VALUES(?,?,?,?,?,?,?,?1,?On,?From)]

**Comment by surajchhetry** [comment]
fixed
