### ISSUE TITLE
Conflict in QueryParameters

### ISSUE THREAD

**Issue by ctizmah** [danfe-tech/simple-libs#7]
While using JDBCTemplate for executeUpdate with list of QueryParameter, I got SQLException stating inclusion of the Unexpected token when there is at least one parameter, whose name begins with one of the earlier parameter.

Some of the list of QueryParameter that caused exception are : ..,enrolled,enrolledOn,enrolledFrom,..

Caught Exception:
java.sql.SQLException: Unexpected token: 1 in statement [INSERT INTO beneficiaries(id_number, id_type, fullname, zone, district, vdc_or_municipality, ward_no, enrolled, enrolled_on, enrolled_from) VALUES(?,?,?,?,?,?,?,?1,?On,?From)]

**Comment by surajchhetry** [comment]
fixed on 0.2.3 version
